# Generated by Django 5.2.8 on 2025-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0010_tappaitinerario_tappaitinerariotranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='colore_percorso',
            field=models.CharField(default='#2E7D32', help_text='Colore del percorso sulla mappa (formato hex, es: #2E7D32)', max_length=7),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='coordinate_tappe',
            field=models.JSONField(blank=True, help_text="JSON con le coordinate delle tappe: [{'nome': 'Tappa 1', 'coords': [lat, lng], 'descrizione': '...', 'order': 1}, ...]", null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='difficolta',
            field=models.CharField(choices=[('facile', 'Facile'), ('media', 'Media'), ('difficile', 'Difficile')], default='facile', help_text='Difficoltà del percorso', max_length=50),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='durata_stimata',
            field=models.CharField(blank=True, help_text="Durata stimata (es: '2-3 ore', 'Mezza giornata')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='icona_percorso',
            field=models.CharField(default='📖', help_text='Emoji/icona per il percorso (es: 📖, 🏛️, 🍷)', max_length=10),
        ),
    ]
