# Generated by Django 5.2.8 on 2026-01-12 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0011_eventoimage_notiziaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='eventi/documenti/')),
                ('titolo', models.CharField(help_text='Titolo descrittivo del documento', max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='parco_verismo.evento')),
            ],
            options={
                'verbose_name': 'Documento Evento',
                'verbose_name_plural': 'Documenti Evento',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='NotiziaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notizie/documenti/')),
                ('titolo', models.CharField(help_text='Titolo descrittivo del documento', max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('notizia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='parco_verismo.notizia')),
            ],
            options={
                'verbose_name': 'Documento Notizia',
                'verbose_name_plural': 'Documenti Notizia',
                'ordering': ['ordine'],
            },
        ),
    ]
