# Generated by Django 5.2.8 on 2026-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0018_alter_itinerario_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='fonte_testo',
            field=models.CharField(choices=[('wikisource', 'WikiSource'), ('internet_archive', 'Internet Archive'), ('gutenberg', 'The Project Gutenberg'), ('altro', 'Altro')], default='wikisource', help_text='Scegli la fonte da mostrare nel bottone', max_length=50, verbose_name='Fonte'),
        ),
        migrations.AddField(
            model_name='opera',
            name='link_fonte',
            field=models.URLField(blank=True, help_text="Link esterno all'opera (WikiSource, Internet Archive, Gutenberg, etc.)", max_length=500),
        ),
    ]
