# Generated by Django 5.2.8 on 2026-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0019_opera_fonte_testo_opera_link_fonte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opera',
            options={'ordering': ['slug'], 'verbose_name': 'Opera', 'verbose_name_plural': 'Opere'},
        ),
        migrations.RemoveField(
            model_name='opera',
            name='anno_pubblicazione',
        ),
        migrations.RemoveField(
            model_name='opera',
            name='link_wikisource',
        ),
        migrations.AlterField(
            model_name='opera',
            name='fonte_testo',
            field=models.CharField(blank=True, choices=[('wikisource', 'WikiSource'), ('internet_archive', 'Internet Archive'), ('gutenberg', 'The Project Gutenberg'), ('altro', 'Altro')], default='altro', help_text='Lascia vuoto per rilevamento automatico dal link', max_length=50, verbose_name='Fonte (opzionale)'),
        ),
        migrations.AlterField(
            model_name='opera',
            name='link_fonte',
            field=models.URLField(help_text="Link all'opera (WikiSource, Internet Archive, Gutenberg, etc.)", max_length=500),
        ),
    ]
