# Generated by Django 5.2.8 on 2026-02-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0020_alter_opera_options_remove_opera_anno_pubblicazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuogoLetterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome del luogo')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('ordine', models.IntegerField(default=0, help_text='Ordine di visualizzazione')),
            ],
            options={
                'verbose_name': 'Luogo Letterario',
                'verbose_name_plural': 'Luoghi Letterari',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OperaInLuogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('romanzi', 'Romanzi'), ('novelle', 'Novelle'), ('teatro', 'Teatro'), ('fiabe', 'Fiabe')], help_text="Categoria letteraria dell'opera in questo luogo", max_length=20, verbose_name='Categoria')),
                ('ordine', models.IntegerField(default=0, help_text='Ordine di visualizzazione nella lista', verbose_name='Ordine')),
                ('luogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opere_luogo', to='parco_verismo.luogoletterario', verbose_name='Luogo')),
                ('opera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luoghi_opera', to='parco_verismo.opera', verbose_name='Opera')),
            ],
            options={
                'verbose_name': 'Opera in Luogo',
                'verbose_name_plural': 'Opere nei Luoghi',
                'ordering': ['luogo__ordine', 'luogo__nome', 'categoria', 'ordine', 'opera__slug'],
                'unique_together': {('opera', 'luogo', 'categoria')},
            },
        ),
    ]
